{
  imports = [
    ./1password.nix
    ./apps.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./catppuccin.nix
    ./cups.nix
    ./env.nix
    ./iphone.nix
    ./hyprland.nix
    ./bilbo-network.nix
    ./nixvim/nixvim.nix
    ./sound.nix
    ./steam.nix
    ./user.nix
    ./bilbo-xserver.nix
  ];
}
