{
  imports = [
    ./1password.nix
    ./apps.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./catppuccin.nix
    ./cups.nix
    ./docker.nix
    ./env.nix
    ./hyprland.nix
    ./iphone.nix
    ./network.nix
    ./nixvim/nixvim.nix
    ./podman.nix
    ./sound.nix
    ./steam.nix
    ./user.nix
    ./virtmanager.nix
    ./virtualbox.nix
    ./xserver.nix
  ];
}
