{
  imports = [
    ./1password.nix
    ./bootloader.nix
    ./cups.nix
    ./docker.nix
    ./env.nix
    ./extra.nix
    ./iphone.nix
    ./network.nix
    ./neovim/nixvim.nix
    ./podman.nix
    ./sound.nix
    ./user.nix
    ./virtmanager.nix
    ./virtualbox.nix
    ./xserver.nix
  ];
}
